import type { Metadata } from "next";

import Link from "next/link";

import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { ApolloWrapper } from "@/lib/apollo-wrapper";

export const metadata: Metadata = {
  title: "Inicio",
  description: "Generated by projects cli",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="container m-auto grid min-h-screen grid-rows-[auto_1fr_auto] gap-8 px-4 font-sans antialiased">
        <header className="text-xl leading-[4rem] font-bold">
          <Link href="/">Inicio</Link>
        </header>
        <ApolloWrapper>{children}</ApolloWrapper>

        <footer className="text-center leading-[4rem] opacity-70">
          Inicio
        </footer>
        <Toaster />
      </body>
    </html>
  );
}
